DEFAULT_STACK = 1000
DEFAULT_NUM_PLAYERS = 2
DEFAULT_NUM_EPOCHS = 2
DEFAULT_NUM_EPISODES = 2
ENV_NAME = 'neuron_poker-v0'
NUM_ROUNDS = 4
ILLEGAL_MOVE_REWARD = -100
DEFAULT_SMALL_BLIND = 1
DEFAULT_BIG_BLIND = 2

RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']
NUM_RANKS = 13
SUITS = ['C', 'D', 'H', 'S']
NUM_SUITS = 4

NUM_CARDS_FOR_PLAYER = 2
TOT_COMMUNITY_CARDS = 5

NUM_RUNS_MONTE_CARLO_STRENGTH_SIMULATION = 1000

CARDS_IN_FLOP = 3
CARDS_IN_TURN = 1
CARDS_IN_RIVER = 1
